# Generated by Django 2.2 on 2020-07-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_completion',
            field=models.DateField(max_length=10, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.TextField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=30, verbose_name='Статус'),
        ),
    ]
