# Generated by Django 2.2 on 2020-07-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200723_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='maxdescription',
            field=models.TextField(max_length=2000, null=True, verbose_name='Подробное описание'),
        ),
    ]
